const documentosExportacion = {
  "Factura comercial": "La factura comercial es un documento esencial en cualquier proceso de exportación. En ella se detalla la transacción entre el exportador y el importador, incluyendo información crítica como el precio unitario de los productos, la descripción precisa de los artículos (en este caso, joyería artesanal), la cantidad de unidades y el valor total de la mercancía. Este documento es requerido por las autoridades aduaneras del país de destino para calcular los aranceles y otros impuestos aplicables a la importación de productos. La factura también puede incluir términos de pago y condiciones de la venta, lo cual es vital para formalizar la operación y evitar malentendidos entre las partes involucradas.",

  "Certificado de origen": "El certificado de origen es un documento oficial que certifica que los productos exportados han sido fabricados o producidos en el país de origen, en este caso, Colombia. Este certificado es especialmente importante porque muchos países tienen acuerdos comerciales que ofrecen aranceles reducidos o exenciones de aranceles a los productos originarios de países específicos. Además, este documento ayuda a garantizar que los productos cumplen con los requisitos de origen preferencial establecidos en tratados de libre comercio, lo cual puede resultar en ventajas económicas significativas para el exportador.",

  "Documentos de transporte": "Los documentos de transporte incluyen el conocimiento de embarque (Bill of Lading) para el transporte marítimo y la guía aérea en caso de transporte aéreo. Estos documentos, emitidos por la empresa de transporte, sirven como prueba de que los productos han sido cargados y enviados a su destino final. Además de su función como prueba de envío, estos documentos también actúan como título de propiedad de la mercancía, permitiendo que el importador la retire una vez que llegue al puerto o aeropuerto del país de destino. Son indispensables para el despacho aduanero, ya que las autoridades aduaneras requieren verificar que la mercancía corresponde con lo que ha sido declarado en la factura comercial y otros documentos relacionados.",

  "Lista de empaque": "La lista de empaque es un documento detallado que describe el contenido de cada paquete, caja o contenedor utilizado para enviar los productos. Incluye información sobre el peso, el volumen, el número de unidades y la descripción detallada de los productos en cada paquete. Esta lista es utilizada por las autoridades aduaneras para verificar la exactitud de los envíos y garantizar que el contenido de cada paquete coincida con lo que se ha declarado en la factura comercial. Además, facilita el proceso de inspección aduanera y ayuda a evitar demoras en el despacho de la mercancía.",

  "Seguro de carga": "El seguro de carga es una opción recomendada, aunque no siempre obligatoria, que protege contra posibles pérdidas o daños que puedan ocurrir durante el transporte de la mercancía. Este tipo de seguro es especialmente importante para productos de alto valor, como la joyería artesanal, ya que cubre el riesgo de robo, daño o pérdida de la carga mientras se encuentra en tránsito. En muchos casos, el seguro es proporcionado por la empresa de transporte, pero también puede ser contratado por separado por el exportador para garantizar una mayor cobertura.",

  "Certificado de calidad o conformidad": "Algunos países importadores requieren un certificado de calidad o conformidad, especialmente cuando los productos deben cumplir con normas específicas de seguridad, calidad o medioambientales. Este certificado garantiza que los productos exportados cumplen con los estándares exigidos por las autoridades del país receptor. En el caso de la joyería artesanal, esto puede incluir certificaciones relacionadas con los materiales utilizados (por ejemplo, metales preciosos o piedras preciosas) y su conformidad con los estándares internacionales de fabricación.",

  "Declaración de exportación": "La declaración de exportación es un documento requerido por las autoridades fiscales del país exportador (como la DIAN en Colombia) para declarar oficialmente que la mercancía está siendo enviada fuera del país. Este documento permite a las autoridades llevar un control estadístico y fiscal sobre las operaciones de comercio exterior. La declaración de exportación es fundamental para cumplir con las normativas locales y para poder procesar los permisos de exportación.",

  "Documentación sanitaria y fitosanitaria": "Aunque es menos común para la joyería, si los productos incluyen materiales de origen natural (como maderas, semillas o pieles), algunos países exigen certificados que aseguren que estos materiales no representan un riesgo para la salud o el ecosistema local. Estos certificados sanitarios y fitosanitarios son necesarios para garantizar que las mercancías no transmitan plagas o enfermedades que puedan afectar el medio ambiente o la salud pública del país receptor.",

  "Contratos y documentos de pago": "Los contratos de exportación y los documentos relacionados con el pago (como cartas de crédito, órdenes de compra o comprobantes de transferencia bancaria) son esenciales para garantizar que ambas partes cumplan con los términos acordados en el contrato de venta. Estos documentos proporcionan seguridad tanto para el exportador como para el importador, asegurando que el pago se realice según lo estipulado y protegiendo a ambas partes en caso de disputas comerciales o impagos."
};

export default documentosExportacion;