const comercioExterior = {
  DIAN: "Entidad colombiana encargada de administrar impuestos nacionales y supervisar operaciones aduaneras.",
  SuperintendenciaDeTransporte: "Organismo regulador que supervisa el sector transporte en Colombia, abarcando todos los medios.",
  OEA: "Certificación para empresas que cumplen estándares de seguridad en comercio exterior, agilizando procesos aduaneros.",
  Incoterms: "Términos comerciales internacionales que definen responsabilidades entre vendedor y comprador.",
  FOB: "El vendedor entrega la mercancía a bordo del barco; desde ahí, los riesgos pasan al comprador.",
  CFR: "El vendedor paga el transporte hasta el puerto de destino, pero el riesgo pasa al comprador al embarcar.",
  CIF: "Similar al CFR pero incluye seguro marítimo contratado por el vendedor hasta el puerto de destino.",
  EXW: "El vendedor entrega la mercancía en su local; el comprador asume todo lo demás.",
  DAP: "El vendedor entrega la mercancía en un lugar acordado, pero el comprador paga impuestos de importación.",
  DDP: "El vendedor cubre todos los costos e impuestos hasta el punto de entrega en el país del comprador.",
  BillOfLading: "Documento que prueba la recepción de la mercancía por el transportista y su contrato de transporte.",
  ConsolidacionDeCarga: "Agrupación de mercancías de diferentes exportadores en un solo envío para reducir costos.",
  ZonaFranca: "Área donde las mercancías pueden almacenarse o procesarse sin pagar impuestos hasta salir de la zona.",
  DeclaracionDeAduanas: "Formulario que detalla mercancías importadas/exportadas y permite aplicar aranceles.",
  DeclaracionDeValor: "Documento que indica el valor real de las mercancías importadas para calcular impuestos.",
  Arancel: "Impuesto aplicado a productos importados o exportados según su tipo y país de origen.",
  CertificadoDeOrigen: "Documento que certifica el país donde fue fabricado o procesado un producto.",
  CertificadosSanitarios: "Garantizan que alimentos, animales o fármacos cumplen normas sanitarias del país destino.",
  Desaduanaje: "Proceso de inspección y aprobación aduanera para liberar mercancías.",
  OperadorLogistico: "Empresa especializada en transporte, almacenamiento y distribución de mercancías.",
  FacturaProforma: "Documento preliminar que describe productos y condiciones antes de la venta oficial.",
  Flete: "Costo por transportar mercancías desde origen hasta destino.",
  TransporteMultimodal: "Uso de varios medios de transporte en una sola operación contractual.",
  DespachoAduanero: "Procedimiento para autorizar legalmente la entrada o salida de mercancías.",
  AgenteAduanero: "Profesional que representa ante la aduana y gestiona trámites legales e impositivos.",
  ContratoDeCompraVentaInternacional: "Acuerdo entre comprador y vendedor de distintos países con condiciones claras.",
  Albaran: "Documento que acredita la entrega de productos y facilita control logístico.",
  FacturaComercial: "Documento oficial que respalda la venta internacional e interviene en trámites aduaneros.",
  ArancelAduanero: "Impuesto basado en la clasificación y origen del producto importado.",
  ImportacionTemporal: "Régimen que permite ingresar bienes sin impuestos por un tiempo limitado.",
  ExportacionTemporal: "Permite enviar productos al exterior para luego reingresarlos al país de origen.",
  PermisoDeImportacion: "Autorización oficial para ingresar productos regulados al país.",
  TransporteInternacional: "Movimiento de mercancías entre países que requiere cumplir normativas globales.",
  AcuerdoComercial: "Pacto entre países que regula el comercio mediante beneficios y normas claras.",
  AgenteDeCarga: "Empresa intermediaria que gestiona logística, transporte y documentación de envíos.",
  CertificadoDeInspeccion: "Documento que verifica que la mercancía cumple especificaciones y estándares.",
  Contenedor: "Estructura metálica estandarizada para transporte seguro y eficiente de mercancías."
};

export default comercioExterior